# Generated by Django 4.1.4 on 2023-06-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propostas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
